namespace MappingAutomationAPI.Models
{
    /// <summary>
    /// Represents a workflow task generated when mapping an issue to an existing or new test.
    /// </summary>
    public class WorkflowTask
    {
        /// <summary>
        /// Unique identifier for this workflow task.
        /// </summary>
        public Guid TaskId { get; set; }

        /// <summary>
        /// UTC timestamp when the task was created.
        /// </summary>
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// The module under test (e.g. “Login”, “QualityMgmt”).
        /// </summary>
        public string Module { get; set; }

        /// <summary>
        /// The natural-language description of the bug or feature request.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// The test scenario chosen or generated by the AI layer.
        /// </summary>
        public string TestScenario { get; set; }

        /// <summary>
        /// Priority level for the task (e.g. Critical, High, Medium).
        /// </summary>
        public string Priority { get; set; }
    }
}
